<?php

use Illuminate\Support\Facades\Blade;
use Pest\Expectation;
use TallStackUi\Components\Alert\Component;
use Tests\Browser\BrowserTestCase;
use Tests\TestCase;

uses(BrowserTestCase::class)->in('Browser')->group('Browser');

uses(TestCase::class)->in('Feature')->group('Feature');

dataset('customization.keys', [
    'ts-ui::customization.accordion',
    'ts-ui::customization.accordion.items',
    'ts-ui::customization.alert',
    'ts-ui::customization.avatar',
    'ts-ui::customization.avatar.group',
    'ts-ui::customization.backToTop',
    'ts-ui::customization.badge',
    'ts-ui::customization.banner',
    'ts-ui::customization.boolean',
    'ts-ui::customization.breadcrumbs',
    'ts-ui::customization.button',
    'ts-ui::customization.button.circle',
    'ts-ui::customization.button.group',
    'ts-ui::customization.calendar',
    'ts-ui::customization.card',
    'ts-ui::customization.carousel',
    'ts-ui::customization.chart',
    'ts-ui::customization.clipboard',
    'ts-ui::customization.commandPalette',
    'ts-ui::customization.dial',
    'ts-ui::customization.dial.items',
    'ts-ui::customization.dialog',
    'ts-ui::customization.dropdown',
    'ts-ui::customization.dropdown.items',
    'ts-ui::customization.dropdown.submenu',
    'ts-ui::customization.environment',
    'ts-ui::customization.errors',
    'ts-ui::customization.floating',
    'ts-ui::customization.form.autocomplete',
    'ts-ui::customization.form.checkbox',
    'ts-ui::customization.form.color',
    'ts-ui::customization.form.currency',
    'ts-ui::customization.form.date',
    'ts-ui::customization.form.error',
    'ts-ui::customization.form.hint',
    'ts-ui::customization.form.input',
    'ts-ui::customization.form.input.select',
    'ts-ui::customization.form.label',
    'ts-ui::customization.form.number',
    'ts-ui::customization.form.password',
    'ts-ui::customization.form.pin',
    'ts-ui::customization.form.radio',
    'ts-ui::customization.form.range',
    'ts-ui::customization.form.tag',
    'ts-ui::customization.form.textarea',
    'ts-ui::customization.form.time',
    'ts-ui::customization.form.toggle',
    'ts-ui::customization.form.upload',
    'ts-ui::customization.form.upload.async',
    'ts-ui::customization.icon',
    'ts-ui::customization.kbd',
    'ts-ui::customization.keyValue',
    'ts-ui::customization.layout',
    'ts-ui::customization.layout.header',
    'ts-ui::customization.link',
    'ts-ui::customization.list',
    'ts-ui::customization.list.items',
    'ts-ui::customization.loading',
    'ts-ui::customization.modal',
    'ts-ui::customization.progress',
    'ts-ui::customization.progress.circle',
    'ts-ui::customization.rating',
    'ts-ui::customization.reaction',
    'ts-ui::customization.select.native',
    'ts-ui::customization.select.styled',
    'ts-ui::customization.sideBar',
    'ts-ui::customization.sideBar.item',
    'ts-ui::customization.sideBar.separator',
    'ts-ui::customization.signature',
    'ts-ui::customization.slide',
    'ts-ui::customization.stats',
    'ts-ui::customization.step',
    'ts-ui::customization.tab',
    'ts-ui::customization.table',
    'ts-ui::customization.themeSwitch',
    'ts-ui::customization.timeline',
    'ts-ui::customization.timeline.items',
    'ts-ui::customization.toast',
    'ts-ui::customization.tooltip',
    'ts-ui::customization.wrapper.input',
    'ts-ui::customization.wrapper.radio',
]);

dataset('customization.components', [
    TallStackUi\Components\Accordion\Items\Component::class,
    TallStackUi\Components\Accordion\Main\Component::class,
    Component::class,
    TallStackUi\Components\Avatar\Component::class,
    TallStackUi\Components\Avatar\Group\Component::class,
    TallStackUi\Components\BackToTop\Component::class,
    TallStackUi\Components\Badge\Component::class,
    TallStackUi\Components\Banner\Component::class,
    TallStackUi\Components\Boolean\Component::class,
    TallStackUi\Components\Breadcrumbs\Component::class,
    TallStackUi\Components\Button\Circle\Component::class,
    TallStackUi\Components\Button\Group\Component::class,
    TallStackUi\Components\Button\Normal\Component::class,
    TallStackUi\Components\Calendar\Component::class,
    TallStackUi\Components\Card\Component::class,
    TallStackUi\Components\Carousel\Component::class,
    TallStackUi\Components\Chart\Component::class,
    TallStackUi\Components\Clipboard\Component::class,
    TallStackUi\Components\CommandPalette\Component::class,
    TallStackUi\Components\Dial\Items\Component::class,
    TallStackUi\Components\Dial\Main\Component::class,
    TallStackUi\Components\Dialog\Component::class,
    TallStackUi\Components\Dropdown\Items\Component::class,
    TallStackUi\Components\Dropdown\Main\Component::class,
    TallStackUi\Components\Dropdown\Submenu\Component::class,
    TallStackUi\Components\Environment\Component::class,
    TallStackUi\Components\Errors\Component::class,
    TallStackUi\Components\Floating\Component::class,
    TallStackUi\Components\Form\Autocomplete\Component::class,
    TallStackUi\Components\Form\Checkbox\Component::class,
    TallStackUi\Components\Form\Color\Component::class,
    TallStackUi\Components\Form\Currency\Component::class,
    TallStackUi\Components\Form\Date\Component::class,
    TallStackUi\Components\Form\Error\Component::class,
    TallStackUi\Components\Form\Hint\Component::class,
    TallStackUi\Components\Form\Input\Component::class,
    TallStackUi\Components\Form\InputSelect\Component::class,
    TallStackUi\Components\Form\Label\Component::class,
    TallStackUi\Components\Form\Number\Component::class,
    TallStackUi\Components\Form\Password\Component::class,
    TallStackUi\Components\Form\Pin\Component::class,
    TallStackUi\Components\Form\Radio\Component::class,
    TallStackUi\Components\Form\Range\Component::class,
    TallStackUi\Components\Form\Select\Native\Component::class,
    TallStackUi\Components\Form\Select\Styled\Component::class,
    TallStackUi\Components\Form\Tag\Component::class,
    TallStackUi\Components\Form\Textarea\Component::class,
    TallStackUi\Components\Form\Time\Component::class,
    TallStackUi\Components\Form\Toggle\Component::class,
    TallStackUi\Components\Form\Upload\Component::class,
    TallStackUi\Components\Kbd\Component::class,
    TallStackUi\Components\KeyValue\Component::class,
    TallStackUi\Components\Layout\Header\Component::class,
    TallStackUi\Components\Layout\Main\Component::class,
    TallStackUi\Components\Layout\SideBar\Item\Component::class,
    TallStackUi\Components\Layout\SideBar\Main\Component::class,
    TallStackUi\Components\Layout\SideBar\Separator\Component::class,
    TallStackUi\Components\Link\Component::class,
    TallStackUi\Components\List\Items\Component::class,
    TallStackUi\Components\List\Main\Component::class,
    TallStackUi\Components\Loading\Component::class,
    TallStackUi\Components\Modal\Component::class,
    TallStackUi\Components\Progress\Bar\Component::class,
    TallStackUi\Components\Progress\Circle\Component::class,
    TallStackUi\Components\Rating\Component::class,
    TallStackUi\Components\Reaction\Component::class,
    TallStackUi\Components\Signature\Component::class,
    TallStackUi\Components\Slide\Component::class,
    TallStackUi\Components\Stats\Component::class,
    TallStackUi\Components\Step\Main\Component::class,
    TallStackUi\Components\Tab\Main\Component::class,
    TallStackUi\Components\Table\Component::class,
    TallStackUi\Components\ThemeSwitch\Component::class,
    TallStackUi\Components\Timeline\Items\Component::class,
    TallStackUi\Components\Timeline\Main\Component::class,
    TallStackUi\Components\Toast\Component::class,
    TallStackUi\Components\Tooltip\Component::class,
    TallStackUi\Components\Wrapper\Input\Component::class,
    TallStackUi\Components\Wrapper\Radio\Component::class,
]);

function colorsDataset(): array
{
    return [
        'primary',
        'secondary',
        'black',
        'slate',
        'gray',
        'zinc',
        'neutral',
        'stone',
        'red',
        'orange',
        'amber',
        'yellow',
        'lime',
        'green',
        'emerald',
        'teal',
        'cyan',
        'sky',
        'blue',
        'indigo',
        'violet',
        'purple',
        'fuchsia',
        'pink',
        'rose',
    ];
}

expect()->extend('render', function (array $data = []): Expectation {
    /** @var Expectation $this */
    $this->value = Blade::render($this->value, $data, true); // @phpstan-ignore-line

    return $this; // @phpstan-ignore-line
});
