#!/usr/bin/env php
<?php

/**
 * Generates .ai/soft-customization-internal-scopes.md by scanning every
 * Blade template under src/resources/views/components/ for `scope="..."`
 * attributes and identifying the nested component that receives the scope.
 *
 * The output is the canonical list of internal scopes used by TallStackUI
 * components when delegating rendering to nested components — for example,
 * `<x-pin />` renders `<x-label />` with scope="form.pin.label" so it can
 * be customized independently of the standalone <x-label />.
 *
 * Usage: php scripts/list-internal-scopes.php
 */
require dirname(__DIR__).'/vendor/autoload.php';

use function Laravel\Prompts\info;

$root = dirname(__DIR__);
$viewsDir = $root.'/src/resources/views/components';
$outputFile = $root.'/.ai/soft-customization-internal-scopes.md';

// Native HTML scope attribute values (e.g. <th scope="col">) — must be ignored.
$htmlScopeValues = ['col', 'row', 'colgroup', 'rowgroup'];

// ── Discovery ────────────────────────────────────────────────

function findBladeFiles(string $dir): array
{
    $files = [];
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS)
    );

    foreach ($iterator as $file) {
        if (str_ends_with($file->getPathname(), '.blade.php')) {
            $files[] = $file->getPathname();
        }
    }

    sort($files);

    return $files;
}

// ── Parsing ──────────────────────────────────────────────────

function findTargetComponent(array $lines, int $scopeLineIndex, int $maxLookback = 15): ?string
{
    $start = max(0, $scopeLineIndex - $maxLookback);

    for ($i = $scopeLineIndex; $i >= $start; $i--) {
        $line = $lines[$i];

        if (preg_match('/TallStackUi::prefix\(\s*[\'"]([^\'"]+)[\'"]\s*\)/', $line, $match)) {
            return $match[1];
        }

        if (preg_match('/<x-([\w\.\-]+)/', $line, $match)) {
            $name = $match[1];

            if ($name === 'slot' || $name === 'dynamic-component') {
                continue;
            }

            return $name;
        }
    }

    return null;
}

// ── Main ─────────────────────────────────────────────────────

$bladeFiles = findBladeFiles($viewsDir);
$entries = [];

foreach ($bladeFiles as $file) {
    $contents = file_get_contents($file);
    $lines = explode("\n", $contents);

    foreach ($lines as $index => $line) {
        if (! preg_match('/\bscope\s*=\s*"([^"]+)"/', $line, $match)) {
            continue;
        }

        $value = $match[1];

        if (in_array($value, $htmlScopeValues, true)) {
            continue;
        }

        $entries[] = [
            'scope' => $value,
            'target' => findTargetComponent($lines, $index),
            'file' => str_replace($root.'/', '', $file),
            'line' => $index + 1,
        ];
    }
}

// Group by file, then merge same-scope entries with line lists.
$grouped = [];

foreach ($entries as $entry) {
    $grouped[$entry['file']][] = $entry;
}

ksort($grouped);

$merged = [];

foreach ($grouped as $file => $items) {
    $byScope = [];

    foreach ($items as $entry) {
        $scope = $entry['scope'];

        if (! isset($byScope[$scope])) {
            $byScope[$scope] = [
                'scope' => $scope,
                'target' => $entry['target'],
                'lines' => [$entry['line']],
                'firstLine' => $entry['line'],
            ];

            continue;
        }

        $byScope[$scope]['lines'][] = $entry['line'];

        if ($byScope[$scope]['target'] === null && $entry['target'] !== null) {
            $byScope[$scope]['target'] = $entry['target'];
        }
    }

    usort($byScope, fn (array $a, array $b): int => $a['firstLine'] <=> $b['firstLine']);

    $merged[$file] = $byScope;
}

// ── Render Markdown ──────────────────────────────────────────

$md = [];
$md[] = '# TallStackUI: Soft Customization Internal Scopes';
$md[] = '';
$md[] = '> Auto-generated by `scripts/list-internal-scopes.php`. Do not edit manually —';
$md[] = '> re-run the script after Blade changes (`php scripts/list-internal-scopes.php`).';
$md[] = '';
$md[] = 'TallStackUI components frequently delegate parts of their rendering to other';
$md[] = 'components. For example, `<x-pin />` renders an internal `<x-label />`, `<x-hint />`';
$md[] = 'and `<x-error />`. To allow each parent to customize its nested children';
$md[] = 'independently of the standalone components, every nested instance is invoked';
$md[] = 'with a `scope="..."` attribute that namespaces the customization.';
$md[] = '';
$md[] = 'This document is the canonical list of every internal scope declared by';
$md[] = "TallStackUI's Blade templates.";
$md[] = '';
$md[] = '## Usage';
$md[] = '';
$md[] = 'In a service provider (typically `AppServiceProvider::boot()`):';
$md[] = '';
$md[] = '```php';
$md[] = "TallStackUi::customize('label', scope: 'form.pin.label')";
$md[] = "    ->block('wrapper', 'your-tailwind-classes');";
$md[] = '```';
$md[] = '';
$md[] = 'Or via the chained API:';
$md[] = '';
$md[] = '```php';
$md[] = 'TallStackUi::customize()';
$md[] = "    ->label(scope: 'form.pin.label')";
$md[] = "    ->block('wrapper', 'your-tailwind-classes');";
$md[] = '```';
$md[] = '';
$md[] = '## Scopes by parent component';
$md[] = '';

foreach ($merged as $file => $items) {
    $heading = preg_replace('#^src/resources/views/components/#', '', $file);
    $heading = preg_replace('#\.blade\.php$#', '', (string) $heading);
    $heading = preg_replace('#/main$#', '', (string) $heading);

    $md[] = "### `{$heading}`";
    $md[] = '';
    $md[] = '| Scope | Target | Line(s) |';
    $md[] = '|-------|--------|---------|';

    foreach ($items as $entry) {
        $scope = '`'.$entry['scope'].'`';
        $target = $entry['target'] !== null ? '`<x-'.$entry['target'].' />`' : '—';
        $lines = implode(', ', array_map(strval(...), $entry['lines']));

        $md[] = "| {$scope} | {$target} | {$lines} |";
    }

    $md[] = '';
}

$distinctScopes = array_unique(array_column($entries, 'scope'));

$md[] = '## Stats';
$md[] = '';
$md[] = '- Total internal scope occurrences: '.count($entries);
$md[] = '- Distinct scopes: '.count($distinctScopes);
$md[] = '- Files declaring scopes: '.count($grouped);
$md[] = '';

file_put_contents($outputFile, implode("\n", $md));

info('Generated '.str_replace($root.'/', '', $outputFile).' with '.count($entries).' occurrence(s).');
