name: Tests

on:
  push:
    branches:
      - 2.x
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    branches:
      - 2.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3 ]
        laravel: [ '11.*' ]
        livewire: [ '^3.0', '^4.0' ]
        shard: [ 1, 2, 3, 4, 5 ]

    name: Laravel:${{ matrix.laravel }} / Livewire:${{ matrix.livewire }} / Shard:${{ matrix.shard }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-    

      - name: Install Node Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm run lint
          npm run build
          npx prettier --check "js/**/*.js"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-progress --ansi --no-update
          composer update --prefer-dist --no-interaction --no-progress --ansi
          composer require livewire/livewire:${{ matrix.livewire }} --no-interaction --no-progress --ansi

      - name: Pint
        run: ./vendor/bin/pint --test --parallel

      - name: Unused Customization Blocks
        run: php scripts/find-unused-customization-blocks.php

      - name: Type Coverage
        run: ./vendor/bin/pest --type-coverage

      - name: Setup Google Chrome
        run: vendor/bin/dusk-updater detect --auto-update

      - name: Clear Orchestra Testbench Cache
        run: ./vendor/bin/testbench view:clear

      - name: Tests
        run: ./vendor/bin/pest --stop-on-failure --shard ${{ matrix.shard }}/5
        env:
          CI: true
