<?php

namespace TallStackUi\Support\Colors\Components;

use TallStackUi\Support\Colors\Concerns\SetupColors;

class TimelineColors
{
    use SetupColors;

    public function colors(): array
    {
        [$marker, $line, $icon] = $this->get('marker', 'line', 'icon');

        $getter = $this->format($this->component->style, $this->component->color); // @phpstan-ignore-line

        return [
            'marker' => data_get($marker, $getter) ?? data_get($this->marker(), $getter),
            'line' => data_get($line, $getter) ?? data_get($this->line(), $getter),
            'icon' => data_get($icon, $getter) ?? data_get($this->icon(), $getter),
        ];
    }

    private function icon(): array
    {
        return [
            'solid' => [
                'black' => 'text-white',
                'primary' => 'text-white',
                'secondary' => 'text-white',
                'slate' => 'text-white',
                'gray' => 'text-white',
                'zinc' => 'text-white',
                'neutral' => 'text-white',
                'stone' => 'text-white',
                'red' => 'text-white',
                'orange' => 'text-white',
                'amber' => 'text-white',
                'yellow' => 'text-white',
                'lime' => 'text-white',
                'green' => 'text-white',
                'emerald' => 'text-white',
                'teal' => 'text-white',
                'cyan' => 'text-white',
                'sky' => 'text-white',
                'blue' => 'text-white',
                'indigo' => 'text-white',
                'violet' => 'text-white',
                'purple' => 'text-white',
                'fuchsia' => 'text-white',
                'pink' => 'text-white',
                'rose' => 'text-white',
                'mauve' => 'text-white',
                'olive' => 'text-white',
                'mist' => 'text-white',
                'taupe' => 'text-white',
            ],
            'light' => [
                'black' => 'text-black dark:text-white',
                'primary' => 'text-primary-700 dark:text-primary-200',
                'secondary' => 'text-secondary-700 dark:text-secondary-200',
                'slate' => 'text-slate-700 dark:text-slate-200',
                'gray' => 'text-gray-700 dark:text-gray-200',
                'zinc' => 'text-zinc-700 dark:text-zinc-200',
                'neutral' => 'text-neutral-700 dark:text-neutral-200',
                'stone' => 'text-stone-700 dark:text-stone-200',
                'red' => 'text-red-700 dark:text-red-200',
                'orange' => 'text-orange-700 dark:text-orange-200',
                'amber' => 'text-amber-700 dark:text-amber-200',
                'yellow' => 'text-yellow-700 dark:text-yellow-200',
                'lime' => 'text-lime-700 dark:text-lime-200',
                'green' => 'text-green-700 dark:text-green-200',
                'emerald' => 'text-emerald-700 dark:text-emerald-200',
                'teal' => 'text-teal-700 dark:text-teal-200',
                'cyan' => 'text-cyan-700 dark:text-cyan-200',
                'sky' => 'text-sky-700 dark:text-sky-200',
                'blue' => 'text-blue-700 dark:text-blue-200',
                'indigo' => 'text-indigo-700 dark:text-indigo-200',
                'violet' => 'text-violet-700 dark:text-violet-200',
                'purple' => 'text-purple-700 dark:text-purple-200',
                'fuchsia' => 'text-fuchsia-700 dark:text-fuchsia-200',
                'pink' => 'text-pink-700 dark:text-pink-200',
                'rose' => 'text-rose-700 dark:text-rose-200',
                'mauve' => 'text-mauve-700 dark:text-mauve-200',
                'olive' => 'text-olive-700 dark:text-olive-200',
                'mist' => 'text-mist-700 dark:text-mist-200',
                'taupe' => 'text-taupe-700 dark:text-taupe-200',
            ],
            'outline' => [
                'black' => 'text-black',
                'primary' => 'text-primary-500',
                'secondary' => 'text-secondary-500',
                'slate' => 'text-slate-500',
                'gray' => 'text-gray-500',
                'zinc' => 'text-zinc-500',
                'neutral' => 'text-neutral-500',
                'stone' => 'text-stone-500',
                'red' => 'text-red-500',
                'orange' => 'text-orange-500',
                'amber' => 'text-amber-500',
                'yellow' => 'text-yellow-500',
                'lime' => 'text-lime-500',
                'green' => 'text-green-500',
                'emerald' => 'text-emerald-500',
                'teal' => 'text-teal-500',
                'cyan' => 'text-cyan-500',
                'sky' => 'text-sky-500',
                'blue' => 'text-blue-500',
                'indigo' => 'text-indigo-500',
                'violet' => 'text-violet-500',
                'purple' => 'text-purple-500',
                'fuchsia' => 'text-fuchsia-500',
                'pink' => 'text-pink-500',
                'rose' => 'text-rose-500',
                'mauve' => 'text-mauve-500',
                'olive' => 'text-olive-500',
                'mist' => 'text-mist-500',
                'taupe' => 'text-taupe-500',
            ],
        ];
    }

    private function line(): array
    {
        $shared = [
            'black' => 'bg-gray-200 dark:bg-dark-600',
            'primary' => 'bg-gray-200 dark:bg-dark-600',
            'secondary' => 'bg-gray-200 dark:bg-dark-600',
            'slate' => 'bg-gray-200 dark:bg-dark-600',
            'gray' => 'bg-gray-200 dark:bg-dark-600',
            'zinc' => 'bg-gray-200 dark:bg-dark-600',
            'neutral' => 'bg-gray-200 dark:bg-dark-600',
            'stone' => 'bg-gray-200 dark:bg-dark-600',
            'red' => 'bg-gray-200 dark:bg-dark-600',
            'orange' => 'bg-gray-200 dark:bg-dark-600',
            'amber' => 'bg-gray-200 dark:bg-dark-600',
            'yellow' => 'bg-gray-200 dark:bg-dark-600',
            'lime' => 'bg-gray-200 dark:bg-dark-600',
            'green' => 'bg-gray-200 dark:bg-dark-600',
            'emerald' => 'bg-gray-200 dark:bg-dark-600',
            'teal' => 'bg-gray-200 dark:bg-dark-600',
            'cyan' => 'bg-gray-200 dark:bg-dark-600',
            'sky' => 'bg-gray-200 dark:bg-dark-600',
            'blue' => 'bg-gray-200 dark:bg-dark-600',
            'indigo' => 'bg-gray-200 dark:bg-dark-600',
            'violet' => 'bg-gray-200 dark:bg-dark-600',
            'purple' => 'bg-gray-200 dark:bg-dark-600',
            'fuchsia' => 'bg-gray-200 dark:bg-dark-600',
            'pink' => 'bg-gray-200 dark:bg-dark-600',
            'rose' => 'bg-gray-200 dark:bg-dark-600',
            'mauve' => 'bg-gray-200 dark:bg-dark-600',
            'olive' => 'bg-gray-200 dark:bg-dark-600',
            'mist' => 'bg-gray-200 dark:bg-dark-600',
            'taupe' => 'bg-gray-200 dark:bg-dark-600',
        ];

        return [
            'solid' => $shared,
            'light' => $shared,
            'outline' => $shared,
        ];
    }

    private function marker(): array
    {
        return [
            'solid' => [
                'black' => 'bg-black ring-4 ring-white dark:ring-dark-700',
                'primary' => 'bg-primary-600 dark:bg-primary-500 ring-4 ring-white dark:ring-dark-700',
                'secondary' => 'bg-secondary-600 dark:bg-secondary-500 ring-4 ring-white dark:ring-dark-700',
                'slate' => 'bg-slate-600 dark:bg-slate-500 ring-4 ring-white dark:ring-dark-700',
                'gray' => 'bg-gray-600 dark:bg-gray-500 ring-4 ring-white dark:ring-dark-700',
                'zinc' => 'bg-zinc-600 dark:bg-zinc-500 ring-4 ring-white dark:ring-dark-700',
                'neutral' => 'bg-neutral-600 dark:bg-neutral-500 ring-4 ring-white dark:ring-dark-700',
                'stone' => 'bg-stone-600 dark:bg-stone-500 ring-4 ring-white dark:ring-dark-700',
                'red' => 'bg-red-600 dark:bg-red-500 ring-4 ring-white dark:ring-dark-700',
                'orange' => 'bg-orange-600 dark:bg-orange-500 ring-4 ring-white dark:ring-dark-700',
                'amber' => 'bg-amber-600 dark:bg-amber-500 ring-4 ring-white dark:ring-dark-700',
                'yellow' => 'bg-yellow-600 dark:bg-yellow-500 ring-4 ring-white dark:ring-dark-700',
                'lime' => 'bg-lime-600 dark:bg-lime-500 ring-4 ring-white dark:ring-dark-700',
                'green' => 'bg-green-600 dark:bg-green-500 ring-4 ring-white dark:ring-dark-700',
                'emerald' => 'bg-emerald-600 dark:bg-emerald-500 ring-4 ring-white dark:ring-dark-700',
                'teal' => 'bg-teal-600 dark:bg-teal-500 ring-4 ring-white dark:ring-dark-700',
                'cyan' => 'bg-cyan-600 dark:bg-cyan-500 ring-4 ring-white dark:ring-dark-700',
                'sky' => 'bg-sky-600 dark:bg-sky-500 ring-4 ring-white dark:ring-dark-700',
                'blue' => 'bg-blue-600 dark:bg-blue-500 ring-4 ring-white dark:ring-dark-700',
                'indigo' => 'bg-indigo-600 dark:bg-indigo-500 ring-4 ring-white dark:ring-dark-700',
                'violet' => 'bg-violet-600 dark:bg-violet-500 ring-4 ring-white dark:ring-dark-700',
                'purple' => 'bg-purple-600 dark:bg-purple-500 ring-4 ring-white dark:ring-dark-700',
                'fuchsia' => 'bg-fuchsia-600 dark:bg-fuchsia-500 ring-4 ring-white dark:ring-dark-700',
                'pink' => 'bg-pink-600 dark:bg-pink-500 ring-4 ring-white dark:ring-dark-700',
                'rose' => 'bg-rose-600 dark:bg-rose-500 ring-4 ring-white dark:ring-dark-700',
                'mauve' => 'bg-mauve-600 dark:bg-mauve-500 ring-4 ring-white dark:ring-dark-700',
                'olive' => 'bg-olive-600 dark:bg-olive-500 ring-4 ring-white dark:ring-dark-700',
                'mist' => 'bg-mist-600 dark:bg-mist-500 ring-4 ring-white dark:ring-dark-700',
                'taupe' => 'bg-taupe-600 dark:bg-taupe-500 ring-4 ring-white dark:ring-dark-700',
            ],
            'light' => [
                'black' => 'bg-black/20 dark:bg-black/50 ring-4 ring-white dark:ring-dark-700',
                'primary' => 'bg-primary-200 dark:bg-primary-800 ring-4 ring-white dark:ring-dark-700',
                'secondary' => 'bg-secondary-200 dark:bg-secondary-800 ring-4 ring-white dark:ring-dark-700',
                'slate' => 'bg-slate-200 dark:bg-slate-800 ring-4 ring-white dark:ring-dark-700',
                'gray' => 'bg-gray-200 dark:bg-gray-800 ring-4 ring-white dark:ring-dark-700',
                'zinc' => 'bg-zinc-200 dark:bg-zinc-800 ring-4 ring-white dark:ring-dark-700',
                'neutral' => 'bg-neutral-200 dark:bg-neutral-800 ring-4 ring-white dark:ring-dark-700',
                'stone' => 'bg-stone-200 dark:bg-stone-800 ring-4 ring-white dark:ring-dark-700',
                'red' => 'bg-red-200 dark:bg-red-800 ring-4 ring-white dark:ring-dark-700',
                'orange' => 'bg-orange-200 dark:bg-orange-800 ring-4 ring-white dark:ring-dark-700',
                'amber' => 'bg-amber-200 dark:bg-amber-800 ring-4 ring-white dark:ring-dark-700',
                'yellow' => 'bg-yellow-200 dark:bg-yellow-800 ring-4 ring-white dark:ring-dark-700',
                'lime' => 'bg-lime-200 dark:bg-lime-800 ring-4 ring-white dark:ring-dark-700',
                'green' => 'bg-green-200 dark:bg-green-800 ring-4 ring-white dark:ring-dark-700',
                'emerald' => 'bg-emerald-200 dark:bg-emerald-800 ring-4 ring-white dark:ring-dark-700',
                'teal' => 'bg-teal-200 dark:bg-teal-800 ring-4 ring-white dark:ring-dark-700',
                'cyan' => 'bg-cyan-200 dark:bg-cyan-800 ring-4 ring-white dark:ring-dark-700',
                'sky' => 'bg-sky-200 dark:bg-sky-800 ring-4 ring-white dark:ring-dark-700',
                'blue' => 'bg-blue-200 dark:bg-blue-800 ring-4 ring-white dark:ring-dark-700',
                'indigo' => 'bg-indigo-200 dark:bg-indigo-800 ring-4 ring-white dark:ring-dark-700',
                'violet' => 'bg-violet-200 dark:bg-violet-800 ring-4 ring-white dark:ring-dark-700',
                'purple' => 'bg-purple-200 dark:bg-purple-800 ring-4 ring-white dark:ring-dark-700',
                'fuchsia' => 'bg-fuchsia-200 dark:bg-fuchsia-800 ring-4 ring-white dark:ring-dark-700',
                'pink' => 'bg-pink-200 dark:bg-pink-800 ring-4 ring-white dark:ring-dark-700',
                'rose' => 'bg-rose-200 dark:bg-rose-800 ring-4 ring-white dark:ring-dark-700',
                'mauve' => 'bg-mauve-200 dark:bg-mauve-800 ring-4 ring-white dark:ring-dark-700',
                'olive' => 'bg-olive-200 dark:bg-olive-800 ring-4 ring-white dark:ring-dark-700',
                'mist' => 'bg-mist-200 dark:bg-mist-800 ring-4 ring-white dark:ring-dark-700',
                'taupe' => 'bg-taupe-200 dark:bg-taupe-800 ring-4 ring-white dark:ring-dark-700',
            ],
            'outline' => [
                'black' => 'bg-white dark:bg-dark-700 border-2 border-black ring-4 ring-white dark:ring-dark-700',
                'primary' => 'bg-white dark:bg-dark-700 border-2 border-primary-500 ring-4 ring-white dark:ring-dark-700',
                'secondary' => 'bg-white dark:bg-dark-700 border-2 border-secondary-500 ring-4 ring-white dark:ring-dark-700',
                'slate' => 'bg-white dark:bg-dark-700 border-2 border-slate-500 ring-4 ring-white dark:ring-dark-700',
                'gray' => 'bg-white dark:bg-dark-700 border-2 border-gray-500 ring-4 ring-white dark:ring-dark-700',
                'zinc' => 'bg-white dark:bg-dark-700 border-2 border-zinc-500 ring-4 ring-white dark:ring-dark-700',
                'neutral' => 'bg-white dark:bg-dark-700 border-2 border-neutral-500 ring-4 ring-white dark:ring-dark-700',
                'stone' => 'bg-white dark:bg-dark-700 border-2 border-stone-500 ring-4 ring-white dark:ring-dark-700',
                'red' => 'bg-white dark:bg-dark-700 border-2 border-red-500 ring-4 ring-white dark:ring-dark-700',
                'orange' => 'bg-white dark:bg-dark-700 border-2 border-orange-500 ring-4 ring-white dark:ring-dark-700',
                'amber' => 'bg-white dark:bg-dark-700 border-2 border-amber-500 ring-4 ring-white dark:ring-dark-700',
                'yellow' => 'bg-white dark:bg-dark-700 border-2 border-yellow-500 ring-4 ring-white dark:ring-dark-700',
                'lime' => 'bg-white dark:bg-dark-700 border-2 border-lime-500 ring-4 ring-white dark:ring-dark-700',
                'green' => 'bg-white dark:bg-dark-700 border-2 border-green-500 ring-4 ring-white dark:ring-dark-700',
                'emerald' => 'bg-white dark:bg-dark-700 border-2 border-emerald-500 ring-4 ring-white dark:ring-dark-700',
                'teal' => 'bg-white dark:bg-dark-700 border-2 border-teal-500 ring-4 ring-white dark:ring-dark-700',
                'cyan' => 'bg-white dark:bg-dark-700 border-2 border-cyan-500 ring-4 ring-white dark:ring-dark-700',
                'sky' => 'bg-white dark:bg-dark-700 border-2 border-sky-500 ring-4 ring-white dark:ring-dark-700',
                'blue' => 'bg-white dark:bg-dark-700 border-2 border-blue-500 ring-4 ring-white dark:ring-dark-700',
                'indigo' => 'bg-white dark:bg-dark-700 border-2 border-indigo-500 ring-4 ring-white dark:ring-dark-700',
                'violet' => 'bg-white dark:bg-dark-700 border-2 border-violet-500 ring-4 ring-white dark:ring-dark-700',
                'purple' => 'bg-white dark:bg-dark-700 border-2 border-purple-500 ring-4 ring-white dark:ring-dark-700',
                'fuchsia' => 'bg-white dark:bg-dark-700 border-2 border-fuchsia-500 ring-4 ring-white dark:ring-dark-700',
                'pink' => 'bg-white dark:bg-dark-700 border-2 border-pink-500 ring-4 ring-white dark:ring-dark-700',
                'rose' => 'bg-white dark:bg-dark-700 border-2 border-rose-500 ring-4 ring-white dark:ring-dark-700',
                'mauve' => 'bg-white dark:bg-dark-700 border-2 border-mauve-500 ring-4 ring-white dark:ring-dark-700',
                'olive' => 'bg-white dark:bg-dark-700 border-2 border-olive-500 ring-4 ring-white dark:ring-dark-700',
                'mist' => 'bg-white dark:bg-dark-700 border-2 border-mist-500 ring-4 ring-white dark:ring-dark-700',
                'taupe' => 'bg-white dark:bg-dark-700 border-2 border-taupe-500 ring-4 ring-white dark:ring-dark-700',
            ],
        ];
    }
}
